# Mathematical Foundations for Machine Learning - Assignment 1
### Course Code: AIMLC ZC416

**Course Objectives Addressed:**
1. **Finding solutions of linear systems** using custom Row Echelon Form (REF) and Reduced Row Echelon Form (RREF) implementations with exact rational arithmetic (`fractions.Fraction`).
2. **Matrix decompositions** from scratch: LU decomposition using elementary matrices, Cholesky decomposition, and Modified Gram-Schmidt QR decomposition.

## 📋 Submission Checklist & Marks Allocation
Use this section as a checklist and planner while preparing your handwritten PDF submission (**`<YOUR_BITSID>.pdf`**).

### General Guidelines:
- **Format:** Single compiled PDF named exactly `<YOUR_BITSID>.pdf`.
- **Execution:** All inputs and outputs must be generated by code. Deterministic/hand-written entries receive **0 marks**.
- **Frozen Randomness:** A random seed (`42`) is set at the beginning. Do not change it, so your handwritten steps and printouts match perfectly.
- **Handwritten Ink:** Explanations, derivations, and observations must be in your own handwriting (on paper or a digital tablet with a stylus). Text typed in a font is not accepted.

### 📊 Question-by-Question Mapping

| Question | Marks | Deliverable (Screenshot) | Handwritten Components | Verifications (Staged in Code) |
| :--- | :---: | :--- | :--- | :--- |
| **Q1(a)** | **2.0** | Core REF & RREF functions/procedures | Brief 2-3 line logic explanation | *None (algorithmic definition)* |
| **Q1(b)** | **1.0** | Solver logic showing pivot/free columns, $x_p$ and homogeneous basis vectors | Explanation of the solution structure | *None (logic definition)* |
| **Q1(c)** | **2.0** | Random $6 \times 9$ matrix $A$, vector $b$, REF, RREF, solutions, and verification | Derivation of general solution from RREF | $A x_p = b$ (residual $\approx 0$), $A v_h = 0$ for all basis vectors |
| **Q2(a)** | **2.0** | LU elementary matrix creation, $L$ and $U$ outputs, and verification | Brief row elimination explanation | $A = LU$ (residual norm $\approx 0$) |
| **Q2(b)** | **1.0** | Cholesky factorization code, $L_{ch}$ output, and verification | Brief comment on positive definiteness | $A = L_{ch} L_{ch}^T$ (residual norm $\approx 0$) |
| **Q2(c)** | **1.0** | Modified Gram-Schmidt QR code, $Q$ and $R$ outputs | Gram-Schmidt projection formulas | *None (logic definition)* |
| **Q2(d)** | **1.0** | Random $7 \times 5$ matrix $A$, $Q$, $R$, and verification | **Observation on the diagonal elements of $R$** | $A = QR$ (norm $\approx 0$), $Q^T Q = I$ (norm $\approx 0$) |

### 🔍 Detailed Submission Checklists

#### **Q1 — Finding Solutions of Linear Systems (Total: 5 Marks)**
- [ ] **Q1(a) (2 Marks):** Screenshot of `compute_ref` and `compute_rref` + 2-3 handwritten lines explaining pivoting/elimination.
- [ ] **Q1(b) (1 Mark):** Screenshot of `solve_system` extraction + handwritten math rules for finding $x_p$ and null basis.
- [ ] **Q1(c) (2 Marks):** Screenshots of random $A$ ($6 \times 9$), $b$, aug-matrix in REF & RREF, output solutions ($x_p, v_i$), verification printouts, and **handwritten general solution** derivation.

#### **Q2 — Matrix Decompositions (Total: 5 Marks)**
- [ ] **Q2(a) (2 Marks):** Screenshot of elementary matrix row-operation functions, output $L$ and $U$ matrices, verification printout, and handwritten explanation of $L = E_1^{-1} \dots E_k^{-1}$.
- [ ] **Q2(b) (1 Mark):** Screenshot of custom Cholesky code, output $L_{ch}$ matrix, verification, and handwritten comment on positive definiteness/diagonal positivity.
- [ ] **Q2(c) (1 Mark):** Screenshot of Modified Gram-Schmidt (MGS) QR algorithm code.
- [ ] **Q2(d) (1 Mark):** Screenshot of random $7 \times 5$ matrix $A$, $Q$, $R$, verification checks, and **handwritten observation on positive diagonal elements of $R$** ($R_{j,j} > 0$).

## Setup & Libraries

In [1]:
import numpy as np
from fractions import Fraction

# Set a random seed to freeze the generator output
# This ensures consistency between the printed code outputs and handwritten answers
np.random.seed(42)

## Q1) Finding Solutions of Linear Systems

### a) Custom REF and RREF Implementation (No high-level built-in functions)

#### 💡 Algorithmic Logic & Row Operations
To solve $Ax=b$, we first construct the augmented matrix $M = [A \mid b]$. The system is solved using two sequential stages:
1. **Forward Elimination (Row Echelon Form - REF):**
   - We scan column-by-column to find a non-zero pivot at or below the current pivot row.
   - If found, we swap that row to the pivot row (**Row Interchange**). If not, we skip the column (marking it as free).
   - We eliminate all entries below the pivot in that column (**Row Replacement**: $R_i \leftarrow R_i - \frac{M_{i,c}}{M_{r,c}} R_r$).
2. **Backward Elimination (Reduced Row Echelon Form - RREF):**
   - For each pivot column, we scale the pivot row so that the pivot entry becomes exactly $1$ (**Row Scaling**: $R_r \leftarrow \frac{1}{M_{r,c}} R_r$).
   - We eliminate all entries *above* the pivot using Row Replacement ($R_i \leftarrow R_i - M_{i,c} R_r$).

---

#### ✍️ Step-by-Step Hand-Worked Example (3×4 Augmented Matrix)
Let's consider a simple augmented matrix $M = [A \mid b]$:
$$M = \begin{bmatrix} 1 & -1 & 1 & \mid & 3 \\ 2 & -1 & 4 & \mid & 8 \\ -1 & 2 & 2 & \mid & 1 \end{bmatrix}$$

**Step 1: Forward Elimination (REF)**
- **Row 1 Pivot ($r=0, c=0$):** Pivot element is $1$ (already in place).
- Eliminate $M_{1,0} = 2$ using $R_2 \leftarrow R_2 - 2R_1$:
  $$M \sim \begin{bmatrix} 1 & -1 & 1 & \mid & 3 \\ 0 & 1 & 2 & \mid & 2 \\ -1 & 2 & 2 & \mid & 1 \end{bmatrix}$$
- Eliminate $M_{2,0} = -1$ using $R_3 \leftarrow R_3 + R_1$:
  $$M \sim \begin{bmatrix} 1 & -1 & 1 & \mid & 3 \\ 0 & 1 & 2 & \mid & 2 \\ 0 & 1 & 3 & \mid & 4 \end{bmatrix}$$
- **Row 2 Pivot ($r=1, c=1$):** Pivot element is $1$ (already in place).
- Eliminate $M_{2,1} = 1$ using $R_3 \leftarrow R_3 - R_2$:
  $$M \sim \begin{bmatrix} 1 & -1 & 1 & \mid & 3 \\ 0 & 1 & 2 & \mid & 2 \\ 0 & 0 & 1 & \mid & 2 \end{bmatrix}$$
This matrix is in **Row Echelon Form (REF)**!

**Step 2: Backward Elimination (RREF)**
- **Row 3 Pivot ($r=2, c=2$):** Pivot element is $1$.
- Eliminate entries above pivot in column 2:
  - $R_2 \leftarrow R_2 - 2R_3$:
    $$M \sim \begin{bmatrix} 1 & -1 & 1 & \mid & 3 \\ 0 & 1 & 0 & \mid & -2 \\ 0 & 0 & 1 & \mid & 2 \end{bmatrix}$$
  - $R_1 \leftarrow R_1 - R_3$:
    $$M \sim \begin{bmatrix} 1 & -1 & 0 & \mid & 1 \\ 0 & 1 & 0 & \mid & -2 \\ 0 & 0 & 1 & \mid & 2 \end{bmatrix}$$
- **Row 2 Pivot ($r=1, c=1$):** Pivot element is $1$.
- Eliminate entries above pivot in column 1:
  - $R_1 \leftarrow R_1 + R_2$:
    $$M \sim \begin{bmatrix} 1 & 0 & 0 & \mid & -1 \\ 0 & 1 & 0 & \mid & -2 \\ 0 & 0 & 1 & \mid & 2 \end{bmatrix}$$
This is the **Reduced Row Echelon Form (RREF)**!
The unique solution is:
$$x_1 = -1,\quad x_2 = -2,\quad x_3 = 2$$

In [2]:
def compute_ref(M):
    """
    Computes Row Echelon Form (REF) of an augmented matrix M using exact Fraction arithmetic.
    """
    m = len(M)
    n = len(M[0]) - 1  # dimensions of coefficient matrix A
    M_ref = [[val for val in row] for row in M]
    r = 0
    c = 0
    pivot_cols = []
    
    while r < m and c < n:
        # Step 1: Find first non-zero element in column c at or below row r
        pivot_row = -1
        for i in range(r, m):
            if M_ref[i][c] != 0:
                pivot_row = i
                break
        
        # If column is all zeros below row r, skip to the next column
        if pivot_row == -1:
            c += 1
            continue
            
        # Step 2: Swap row r and pivot_row (Row Interchange)
        M_ref[r], M_ref[pivot_row] = M_ref[pivot_row], M_ref[r]
        pivot_cols.append(c)
        
        # Step 3: Eliminate entries below pivot element (Row Replacement)
        for i in range(r + 1, m):
            if M_ref[i][c] != 0:
                factor = M_ref[i][c] / M_ref[r][c]
                for j in range(c, n + 1):
                    M_ref[i][j] = M_ref[i][j] - factor * M_ref[r][j]
        r += 1
        c += 1
        
    return M_ref, pivot_cols

def compute_rref(M_ref, pivot_cols):
    """
    Computes Reduced Row Echelon Form (RREF) from the REF matrix and identified pivot columns.
    """
    m = len(M_ref)
    n = len(M_ref[0]) - 1
    M_rref = [[val for val in row] for row in M_ref]
    
    for r, c in enumerate(pivot_cols):
        # Step 1: Normalize pivot row to make the leading entry 1 (Row Scaling)
        pivot_val = M_rref[r][c]
        for j in range(c, n + 1):
            M_rref[r][j] /= pivot_val
            
        # Step 2: Eliminate all entries above and below pivot in column c
        for i in range(m):
            if i != r and M_rref[i][c] != 0:
                factor = M_rref[i][c]
                for j in range(c, n + 1):
                    M_rref[i][j] -= factor * M_rref[r][j]
                    
    return M_rref

### b) Identifying Pivot/Non-Pivot Columns and Finding System Solutions

#### 📊 Mathematical Structure of the Solution
From the Reduced Row Echelon Form (RREF) of the augmented matrix $[A \mid b]$, we can extract the complete set of solutions:
1. **Pivot Columns (Basic Variables):** Columns containing the leading $1$ of any row. These variables are solved in terms of the free variables.
2. **Non-Pivot Columns (Free Variables):** Columns that do not contain a leading $1$. We can assign arbitrary values (parameters) to these variables.
3. **Particular Solution ($x_p$):** A specific solution to $Ax=b$. It is computed by setting all free variables to $0$. The basic variables then simply take the values of the right-hand side vector $b$ from the corresponding rows of the RREF.
4. **Homogeneous Solutions (Null-Space Basis $v_k$):** Solutions to the homogeneous equation $Ax=0$. For each free variable $x_k$:
   - Set $x_k = 1$ and all other free variables to $0$.
   - For each basic variable $x_c$ associated with pivot column $c$ in row $r$, we have:
     $$x_c + M_{\text{RREF}}[r][k] \cdot x_k = 0 \implies x_c = -M_{\text{RREF}}[r][k]$$
   - This constructs a basis vector $v_k$ of the null space.
5. **General Solution:**
   $$x = x_p + \sum_{k \in \text{free}} \alpha_k v_k$$
   where $\alpha_k \in \mathbb{R}$ are arbitrary constants.

In [3]:
def solve_system(M_rref, pivot_cols):
    """
    Extracts pivot and free columns, computes particular solution x_p and null-space basis vectors.
    """
    m = len(M_rref)
    n = len(M_rref[0]) - 1
    
    # Check for consistency (no row [0 0 ... 0 | b] where b != 0)
    for i in range(m):
        all_zeros = True
        for j in range(n):
            if M_rref[i][j] != 0:
                all_zeros = False
                break
        if all_zeros and M_rref[i][n] != 0:
            return "System is Inconsistent (No solution)"
            
    pivot_set = set(pivot_cols)
    free_cols = [j for j in range(n) if j not in pivot_set]
    
    # 1. Particular solution x_p (set free variables to 0)
    x_p = [Fraction(0)] * n
    row_to_pivot = {r: c for r, c in enumerate(pivot_cols)}
    for r, c in row_to_pivot.items():
        x_p[c] = M_rref[r][n]
        
    # 2. Homogeneous solutions basis (null space solutions Ax = 0)
    null_basis = []
    for k in free_cols:
        v = [Fraction(0)] * n
        v[k] = Fraction(1)  # set this free variable to 1, others to 0
        for r, c in row_to_pivot.items():
            # x_c + M_rref[r][k]*x_k = 0 => x_c = -M_rref[r][k]
            v[c] = -M_rref[r][k]
        null_basis.append(v)
        
    return {
        'particular': x_p,
        'null_basis': null_basis,
        'pivot_cols': pivot_cols,
        'free_cols': free_cols
    }

### c) Execution on a Random $6 \times 9$ Matrix and Validation

#### ✍️ Derivation of the General Solution from RREF
Given the randomly generated $6 \times 9$ matrix $A$ and vector $b$, the execution of RREF yields the following:
- **Basic Variables (Pivot Columns):** $x_0, x_1, x_2, x_3, x_4, x_5$ (Columns 0, 1, 2, 3, 4, 5).
- **Free Variables (Non-Pivot Columns):** $x_6, x_7, x_8$ (Columns 6, 7, 8).

Expressing the basic variables in terms of the free variables from the rows of RREF:
1. Row 0: $x_0 - \frac{14,653}{6,805} x_6 + \frac{376}{6,805} x_7 - \frac{1,343}{6,805} x_8 = -\frac{12,819}{6,805}$
   $$\implies x_0 = -\frac{12,819}{6,805} + \frac{14,653}{6,805} x_6 - \frac{376}{6,805} x_7 + \frac{1,343}{6,805} x_8$$
2. Row 1: $x_1 + \frac{18,466}{6,805} x_6 - \frac{3,597}{6,805} x_7 + \frac{2,586}{6,805} x_8 = \frac{3,853}{6,805}$
   $$\implies x_1 = \frac{3,853}{6,805} - \frac{18,466}{6,805} x_6 + \frac{3,597}{6,805} x_7 - \frac{2,586}{6,805} x_8$$
3. Row 2: $x_2 + \frac{1,805}{1,361} x_6 - \frac{117}{1,361} x_7 + \frac{436}{1,361} x_8 = \frac{2,979}{1,361}$
   $$\implies x_2 = \frac{2,979}{1,361} - \frac{1,805}{1,361} x_6 + \frac{117}{1,361} x_7 - \frac{436}{1,361} x_8$$
4. Row 3: $x_3 + \frac{18,173}{6,805} x_6 - \frac{9,396}{6,805} x_7 + \frac{3,083}{6,805} x_8 = -\frac{15,061}{6,805}$
   $$\implies x_3 = -\frac{15,061}{6,805} - \frac{18,173}{6,805} x_6 + \frac{9,396}{6,805} x_7 - \frac{3,083}{6,805} x_8$$
5. Row 4: $x_4 - \frac{894}{6,805} x_6 - \frac{1,622}{6,805} x_7 - \frac{179}{6,805} x_8 = \frac{14,288}{6,805}$
   $$\implies x_4 = \frac{14,288}{6,805} + \frac{894}{6,805} x_6 + \frac{1,622}{6,805} x_7 + \frac{179}{6,805} x_8$$
6. Row 5: $x_5 - \frac{712}{1,361} x_6 - \frac{1,578}{1,361} x_7 - \frac{785}{1,361} x_8 = \frac{814}{1,361}$
   $$\implies x_5 = \frac{814}{1,361} + \frac{712}{1,361} x_6 + \frac{1,578}{1,361} x_7 + \frac{785}{1,361} x_8$$

Substituting free variables $x_6, x_7, x_8 \rightarrow 0$ yields the **Particular Solution ($x_p$)**:
$$x_p = \begin{bmatrix} -\frac{12,819}{6,805} & \frac{3,853}{6,805} & \frac{2,979}{1,361} & -\frac{15,061}{6,805} & \frac{14,288}{6,805} & \frac{814}{1,361} & 0 & 0 & 0 \end{bmatrix}^T$$

By setting each free variable to $1$ individually while holding others at $0$, we obtain the **Homogeneous Basis Vectors ($v_1, v_2, v_3$)**:
$$v_1 = \begin{bmatrix} \frac{14,653}{6,805} & -\frac{18,466}{6,805} & -\frac{1,805}{1,361} & -\frac{18,173}{6,805} & \frac{894}{6,805} & \frac{712}{1,361} & 1 & 0 & 0 \end{bmatrix}^T$$
$$v_2 = \begin{bmatrix} -\frac{376}{6,805} & \frac{3,597}{6,805} & \frac{117}{1,361} & \frac{9,396}{6,805} & \frac{1,622}{6,805} & \frac{1,578}{1,361} & 0 & 1 & 0 \end{bmatrix}^T$$
$$v_3 = \begin{bmatrix} \frac{1,343}{6,805} & -\frac{2,586}{6,805} & -\frac{436}{1,361} & -\frac{3,083}{6,805} & \frac{179}{6,805} & \frac{785}{1,361} & 0 & 0 & 1 \end{bmatrix}^T$$

The general solution is:
$$x = x_p + x_6 v_1 + x_7 v_2 + x_8 v_3$$
which matches the verification outputs generated by the code.

In [4]:
# 1. Generate random matrix A and vector b
A_rand = np.random.randint(-5, 6, size=(6, 9))
b_rand = np.random.randint(-5, 6, size=(6, 1))

print("=== RANDOM COEFFICIENT MATRIX A (6 x 9) ===")
print(A_rand)
print("\n=== RANDOM VECTOR b (6 x 1) ===")
print(b_rand)

# 2. Convert to augmented matrix of exact Fractions
M_augmented = []
for i in range(6):
    row = [Fraction(int(val)) for val in A_rand[i]]
    row.append(Fraction(int(b_rand[i][0])))
    M_augmented.append(row)

# 3. Run Gaussian Elimination and Gauss-Jordan to find REF and RREF
M_ref, pivot_cols = compute_ref(M_augmented)
M_rref = compute_rref(M_ref, pivot_cols)

# 4. Extract solutions
sol = solve_system(M_rref, pivot_cols)

print("\n=== PIVOT AND FREE COLUMNS ===")
print(f"Pivot Columns: {sol['pivot_cols']}")
print(f"Free Columns (non-pivot): {sol['free_cols']}")

print("\n=== PARTICULAR SOLUTION x_p ===")
print([str(x) for x in sol['particular']])

print("\n=== HOMOGENEOUS SOLUTION BASIS (Null Space of A) ===")
for idx, basis_vec in enumerate(sol['null_basis']):
    print(f"Basis Vector {idx+1} (Free variable x_{sol['free_cols'][idx]} = 1):")
    print([str(val) for val in basis_vec])

# 5. Verification using floating point math
x_p_float = np.array([float(val) for val in sol['particular']])
err_p = np.linalg.norm(A_rand @ x_p_float - b_rand.flatten())

print("\n=== VERIFICATION ===")
print(f"Particular solution validation: A * x_p = b ? {err_p < 1e-12} (Error norm: {err_p:.4e})")

for idx, basis_vec in enumerate(sol['null_basis']):
    v_float = np.array([float(val) for val in basis_vec])
    err_n = np.linalg.norm(A_rand @ v_float)
    print(f"Null basis vector {idx+1} validation: A * v{idx+1} = 0 ? {err_n < 1e-12} (Error norm: {err_n:.4e})")

=== RANDOM COEFFICIENT MATRIX A (6 x 9) ===
[[ 1 -2  5  2 -1  1  4 -3  1]
 [ 5  5  2 -1 -2  2  2 -3  0]
 [-1 -4  2  0 -4 -1 -5  4  0]
 [ 3 -5  5  5  4 -3  1 -2  3]
 [-3 -1 -3  1 -1  3  1 -4 -2]
 [ 3 -4  4  3  4 -1 -4 -2  1]]

=== RANDOM VECTOR b (6 x 1) ===
[[ 2]
 [-3]
 [-5]
 [-2]
 [-4]
 [ 2]]

=== PIVOT AND FREE COLUMNS ===
Pivot Columns: [0, 1, 2, 3, 4, 5]
Free Columns (non-pivot): [6, 7, 8]

=== PARTICULAR SOLUTION x_p ===
['-12819/6805', '3853/6805', '2979/1361', '-15061/6805', '14288/6805', '814/1361', '0', '0', '0']

=== HOMOGENEOUS SOLUTION BASIS (Null Space of A) ===
Basis Vector 1 (Free variable x_6 = 1):
['14653/6805', '-18466/6805', '-1805/1361', '-18173/6805', '894/6805', '712/1361', '1', '0', '0']
Basis Vector 2 (Free variable x_7 = 1):
['-376/6805', '3597/6805', '117/1361', '9396/6805', '1622/6805', '1578/1361', '0', '1', '0']
Basis Vector 3 (Free variable x_8 = 1):
['1343/6805', '-2586/6805', '-436/1361', '-3083/6805', '179/6805', '785/1361', '0', '0', '1']

=== VERIFICA

## Q2) Matrix Decompositions

### a) LU Decomposition using Elementary Matrices

#### 💡 Row Operations and Inverse Elementary Matrices
To decompose a symmetric positive definite (SPD) matrix $A$ into $LU$:
1. We apply a series of elementary row operations (row replacements) to eliminate the elements below the main diagonal, transforming $A$ into an upper triangular matrix $U$.
2. Each elementary row operation of the form $R_i \leftarrow R_i - c R_j$ corresponds to multiplying $A$ on the left by an elementary matrix $E_{i,j}(-c)$.
3. If $k$ row operations are performed, we have:
   $$E_k \dots E_2 E_1 A = U$$
4. Since each elementary matrix is invertible, we can write:
   $$A = E_1^{-1} E_2^{-1} \dots E_k^{-1} U = L U$$
   where $L = E_1^{-1} E_2^{-1} \dots E_k^{-1}$ is unit lower triangular. The inverse elementary matrix $E_{i,j}^{-1}(-c) = E_{i,j}(c)$ simply has $+c$ at position $(i,j)$ instead of $-c$.

In [5]:
# 1. Generate a symmetric positive definite matrix A
B = np.random.randint(-3, 4, size=(4, 4)).astype(float)
A_spd = B.T @ B + np.eye(4) * 0.5
print("=== SPD Matrix A ===")
print(A_spd)

# 2. Custom LU decomposition tracking elementary matrices
def lu_decomposition_elementary(A):
    n = len(A)
    U = np.array(A, dtype=float)
    L = np.eye(n, dtype=float)
    
    for j in range(n):
        pivot = U[j, j]
        for i in range(j + 1, n):
            factor = U[i, j] / pivot
            if factor != 0:
                # Construct elementary matrix E
                E = np.eye(n, dtype=float)
                E[i, j] = -factor
                
                # Construct its inverse
                E_inv = np.eye(n, dtype=float)
                E_inv[i, j] = factor
                
                print(f"\nConstructed Elementary Matrix E for Row {i} = Row {i} - ({factor:.4f}) * Row {j}:")
                print(E)
                
                # Perform row replacement on U and accumulate inverse row operation in L
                U = E @ U
                L = L @ E_inv
                
    return L, U

L_lu, U_lu = lu_decomposition_elementary(A_spd)

print("\n=== LOWER TRIANGULAR MATRIX L ===")
print(L_lu)
print("\n=== UPPER TRIANGULAR MATRIX U ===")
print(U_lu)

# 3. Verification
err_lu = np.linalg.norm(A_spd - L_lu @ U_lu)
print("\n=== LU DECOMPOSITION VERIFICATION ===")
print(f"Reconstruction check: A = L * U ? {err_lu < 1e-12}")
print(f"Frobenius norm error ||A - L*U||_F: {err_lu:.4e}")

=== SPD Matrix A ===
[[  5.5  -1.   -2.    2. ]
 [ -1.   21.5  -6.  -18. ]
 [ -2.   -6.   12.5   4. ]
 [  2.  -18.    4.   16.5]]

Constructed Elementary Matrix E for Row 1 = Row 1 - (-0.1818) * Row 0:
[[1.         0.         0.         0.        ]
 [0.18181818 1.         0.         0.        ]
 [0.         0.         1.         0.        ]
 [0.         0.         0.         1.        ]]

Constructed Elementary Matrix E for Row 2 = Row 2 - (-0.3636) * Row 0:
[[1.         0.         0.         0.        ]
 [0.         1.         0.         0.        ]
 [0.36363636 0.         1.         0.        ]
 [0.         0.         0.         1.        ]]

Constructed Elementary Matrix E for Row 3 = Row 3 - (0.3636) * Row 0:
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [-0.36363636  0.          0.          1.        ]]

Constructed Elementary Matrix E for Row 2 = Row 2 - (-0.2985) * Row 1:


### b) Cholesky Decomposition

#### 💡 Recurrence Relation and Positive Definiteness
For a symmetric positive definite (SPD) matrix $A$, Cholesky decomposition finds a unique lower triangular matrix $L_{ch}$ with positive diagonal elements such that $A = L_{ch} L_{ch}^T$. The entries of $L_{ch}$ are calculated using the Cholesky-Banachiewicz recurrence relations:
1. **Diagonal entries:**
   $$L_{i,i} = \sqrt{A_{i,i} - \sum_{k=0}^{i-1} L_{i,k}^2}$$
2. **Off-diagonal entries ($j < i$):**
   $$L_{i,j} = \frac{1}{L_{j,j}} \left( A_{i,j} - \sum_{k=0}^{j-1} L_{i,k} L_{j,k} \right)$$

*Note on Positive Definiteness:* A matrix $A$ is positive definite if $x^T A x > 0$ for all $x \neq 0$. This property guarantees that the term inside the square root for the diagonal entries $L_{i,i}$ is always strictly positive, ensuring that $L_{ch}$ is real-valued and has a positive diagonal.

In [6]:
def cholesky_decomposition(A):
    """
    Computes Cholesky decomposition of symmetric positive definite matrix A.
    """
    n = len(A)
    L = np.zeros((n, n), dtype=float)
    for i in range(n):
        for j in range(i + 1):
            if i == j:
                val = A[i, i] - np.sum(L[i, :i]**2)
                if val < 0:
                    raise ValueError("Matrix is not positive definite.")
                L[i, i] = np.sqrt(val)
            else:
                L[i, j] = (A[i, j] - np.sum(L[i, :j] * L[j, :j])) / L[j, j]
    return L

L_ch = cholesky_decomposition(A_spd)
print("=== LOWER TRIANGULAR MATRIX L_ch (Cholesky) ===")
print(L_ch)

# Verification
err_ch = np.linalg.norm(A_spd - L_ch @ L_ch.T)
print("\n=== CHOLESKY DECOMPOSITION VERIFICATION ===")
print(f"Reconstruction check: A = L_ch * L_ch^T ? {err_ch < 1e-12}")
print(f"Frobenius norm error ||A - L_ch*L_ch^T||_F: {err_ch:.4e}")

=== LOWER TRIANGULAR MATRIX L_ch (Cholesky) ===
[[ 2.34520788  0.          0.          0.        ]
 [-0.42640143  4.61716166  0.          0.        ]
 [-0.85280287 -1.37825721  3.14215441  0.        ]
 [ 0.85280287 -3.81974142 -0.1710016   1.07380688]]

=== CHOLESKY DECOMPOSITION VERIFICATION ===
Reconstruction check: A = L_ch * L_ch^T ? True
Frobenius norm error ||A - L_ch*L_ch^T||_F: 3.9721e-15


### c) QR Decomposition using Modified Gram-Schmidt (MGS)

#### 💡 Gram-Schmidt Projection and Orthonormalization
QR decomposition factorizes an $m \times n$ matrix $A$ (with $m \ge n$ and linearly independent columns) into $Q R$, where $Q$ is an $m \times n$ matrix with orthonormal columns ($Q^T Q = I$), and $R$ is an $n \times n$ upper triangular matrix.
The Modified Gram-Schmidt (MGS) algorithm computes this column-by-column:
For each column $j = 0, \dots, n-1$:
1. Set $v_j = a_j$ (the $j$-th column of $A$).
2. For each previous column $i = 0, \dots, j-1$:
   - Compute the projection coefficient (dot product):
     $$R_{i,j} = q_i^T v_j$$
   - Subtract the projection from $v_j$ to make it orthogonal to $q_i$:
     $$v_j \leftarrow v_j - R_{i,j} q_i$$
3. Compute the norm of the orthogonalized vector:
   $$R_{j,j} = \|v_j\|_2$$
4. Normalize the vector to get the $j$-th column of $Q$:
   $$q_j = \frac{v_j}{R_{j,j}}$$

In [7]:
def qr_decomposition(A):
    """
    Decomposes an m x n matrix A (m > n) into Q (m x n) and R (n x n) using Modified Gram-Schmidt.
    """
    m, n = A.shape
    Q = np.zeros((m, n), dtype=float)
    R = np.zeros((n, n), dtype=float)
    V = A.copy().astype(float)  # column vectors working copy
    
    for j in range(n):
        # Orthogonalization step
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], V[:, j])
            V[:, j] = V[:, j] - R[i, j] * Q[:, i]
            
        # Normalization step
        norm = np.linalg.norm(V[:, j])
        if norm < 1e-12:
            raise ValueError(f"Matrix columns are not linearly independent at index {j}")
        R[j, j] = norm
        Q[:, j] = V[:, j] / norm
        
    return Q, R

### d) Execution on a Random $7 \times 5$ Matrix and Observation
We generate a random $7 \times 5$ matrix with linearly independent columns, run the Gram-Schmidt decomposition, verify the output conditions ($A = QR$ and $Q^T Q = I$), and record mathematical observations.

In [8]:
# 1. Generate random 7 x 5 matrix with linearly independent columns
B_qr = np.random.randint(-4, 5, size=(7, 5)).astype(float)
print("=== RANDOM MATRIX A (7 x 5) ===")
print(B_qr)

# 2. Run custom QR decomposition
Q_qr, R_qr = qr_decomposition(B_qr)

print("\n=== ORTHONORMAL MATRIX Q (7 x 5) ===")
print(Q_qr)
print("\n=== UPPER TRIANGULAR MATRIX R (5 x 5) ===")
print(R_qr)

# 3. Verification
err_qr = np.linalg.norm(B_qr - Q_qr @ R_qr)
err_q_orth = np.linalg.norm(Q_qr.T @ Q_qr - np.eye(5))
print("\n=== QR DECOMPOSITION VERIFICATION ===")
print(f"Reconstruction check: A = Q * R ? {err_qr < 1e-12} (Error norm: {err_qr:.4e})")
print(f"Q orthogonality check: Q^T * Q = I ? {err_q_orth < 1e-12} (Error norm: {err_q_orth:.4e})")

print("\n=== OBSERVATION ON DIAGONAL ELEMENTS OF R ===")
diag_R = np.diag(R_qr)
print(f"Diagonal elements of R: {[round(x, 8) for x in diag_R]}")

=== RANDOM MATRIX A (7 x 5) ===
[[-1.  3.  2.  4.  3.]
 [ 0. -3.  0.  3.  4.]
 [ 4. -4.  4.  2.  4.]
 [ 3. -4.  3.  3. -2.]
 [-4.  3. -2. -2. -4.]
 [ 0.  2.  4.  2.  4.]
 [ 3. -3. -4.  2.  2.]]

=== ORTHONORMAL MATRIX Q (7 x 5) ===
[[-0.14002801  0.45456774  0.16589163  0.71176926 -0.14187104]
 [ 0.         -0.68860261  0.25143853  0.51374465  0.41912081]
 [ 0.56011203  0.01800268  0.34449969 -0.17840995  0.28449588]
 [ 0.42008403 -0.21603219  0.34218761  0.12961177 -0.77094061]
 [-0.56011203 -0.24753689  0.01907465  0.03960939 -0.24291418]
 [ 0.          0.45906841  0.3918973   0.14345829  0.26362486]
 [ 0.42008403  0.01350201 -0.72079046  0.39833711  0.02043685]]

=== UPPER TRIANGULAR MATRIX R (5 x 5) ===
[[ 7.14142843 -7.28145644  2.66053216  3.78075623  4.06081224]
 [ 0.          4.35664919  2.61038898  0.58058651  1.96679307]
 [ 0.          0.          7.14894664  2.43750873  2.24676226]
 [ 0.          0.          0.          5.42469841  4.42949282]
 [ 0.          0.          0.  

### Observation on the diagonal elements of $R$:
1. **Strict Positivity:** All diagonal elements $R_{j,j}$ are strictly positive ($R_{j,j} > 0$). In the Gram-Schmidt process, the diagonal elements represent the Euclidean norm (length) of the orthogonalized column vectors $v'_j$ prior to normalization: $R_{j,j} = \|v'_j\|_2$.
2. **Linear Independence:** Since the columns of $A$ are linearly independent, no column vector can lie in the span of the preceding columns. Thus, the orthogonalized vectors $v'_j$ are guaranteed to be non-zero vectors, and their norms $R_{j,j}$ must be strictly positive. If the columns were linearly dependent, at least one diagonal element of $R$ would be zero.